image:
  name: atlassian/default-image:3
  entrypoint: ["/bin/sh", "-c"]

stages:
  - check
  - tag

variables:
  GIT_STRATEGY: clone

check_shell:
  stage: check
  image: koalaman/shellcheck-alpine:latest
  script:
    - shellcheck $(find . -type f -name "*.sh" | xargs)

# check_tag:
#   stage: check
#   script:
#     - git remote set-url origin $CI_REPOSITORY_URL
#     - source version.sh
#     - git tag -a $VERSION -m "$CI_COMMIT_TIMESTAMP - Version $VERSION"

# tag:
#   stage: tag
#   rules:
#     - if: $CI_COMMIT_BRANCH == "main"
#       when: always
#       allow_failure: true
#   script:
#     - echo 'Tag'
