version: "3"

networks:
  xcom_network:
    driver: bridge

volumes:
  elasticsearch:

services:
  nginx:
    build: nginx
    # image: xcommagento/docker-nginx:latest
    # restart: always
    ports:
      - 80:80
      - 443:443
    working_dir: /etc/nginx/sites-enabled
    volumes:
      - ./nginx/site-templates:/etc/nginx/site-templates:ro
      - installdirectory/data/shared/sites:/data/shared/sites
      - installdirectory/data/shared/sockets:/data/shared/sockets
      - installdirectory/data/shared/media:/data/shared/media
      - ~/.config/docker-setup.config:/root/.config/docker-setup.config:ro
    networks:
      - xcom_network
  mysql57:
    image: mysql:5.7
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=xcom
    ports:
      - 3306:3306
    volumes:
      - installdirectory/data/mysql57:/var/lib/mysql
      - ./mysql57/conf.d:/etc/mysql/conf.d:ro
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
    networks:
      - xcom_network
  mysql80:
    image: mysql:8.0
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=xcom
    ports:
      - 3308:3306
    volumes:
      - installdirectory/data/mysql80:/var/lib/mysql
      - ./mysql80/conf.d:/etc/mysql/conf.d:ro
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
    networks:
      - xcom_network
  redis:
    image: redis:6.2-alpine
    # restart: always
    ports:
      - 6379:6379
    volumes:
      - installdirectory/data/redis:/data
    networks:
      - xcom_network
  mailtrap:
    image: xcommagento/docker-mailtrap:latest
    # restart: always
    ports:
      - 8085:80
      - 0.0.0.0:25:25
    networks:
      - xcom_network
