version: "3.4"

services:
  nginx:
    build: nginx
    # restart: always
    network_mode: "host"
    working_dir: /etc/nginx/sites-enabled
    volumes:
      - ./nginx/site-templates:/etc/nginx/site-templates:ro
      - installdirectory/data/shared/sites:/data/shared/sites
      - installdirectory/data/shared/sockets:/data/shared/sockets
      - installdirectory/data/shared/media:/data/shared/media
      - /etc/xcomuser:/etc/xcomuser:ro

  mysql57:
    image: mysql:5.7
    # restart: always
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=xcom
  #  ports:
  #    - 3306:3306
    volumes:
      - installdirectory/data/mysql57:/var/lib/mysql
      - ./mysql57/conf.d:/etc/mysql/conf.d:ro

  mysql80:
    image: mysql:8.0
    # restart: always
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=xcom
    volumes:
      - installdirectory/data/mysql80:/var/lib/mysql
      - ./mysql80/conf.d:/etc/mysql/conf.d:ro

  redis:
    image: redis:5.0
    # restart: always
    network_mode: "host"
  #  ports:
  #    - 6379:6379      
    volumes:
      - installdirectory/data/redis28:/data

  mailtrap:
    build: mailtrap
    # restart: always
    network_mode: "host"
  #  ports:
  #    - 8085:8085
  #    - 25:25

  elasticsearch6:
    build: elasticsearch6
    # restart: always
    # network_mode: "host"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  elasticsearch7:
    build: elasticsearch7
    # restart: always
    # network_mode: "host"
    ports:
      - 9400:9200
      - 9500:9300
    environment:
      - discovery.type=single-node

