version: "3"

volumes:
  elasticsearch:

services:
  nginx:
    build: nginx
    # restart: always
    ports:
      - 80:80
      - 443:443
    working_dir: /etc/nginx/sites-enabled
    volumes:
      - ./nginx/site-templates:/etc/nginx/site-templates:ro
      - installdirectory/data/shared/sites:/data/shared/sites
      - installdirectory/data/shared/sockets:/data/shared/sockets
      - installdirectory/data/shared/media:/data/shared/media
      - /etc/xcomuser:/etc/xcomuser:ro

  mysql57:
    image: mysql:5.7
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=xcom
    ports:
      - 3306:3306
    volumes:
      - installdirectory/data/mysql57:/var/lib/mysql
      - ./mysql57/conf.d:/etc/mysql/conf.d:ro

  mysql80:
    image: mysql:8.0
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=xcom
    ports:
      - 3308:3308
    volumes:
      - installdirectory/data/mysql80:/var/lib/mysql
      - ./mysql80/conf.d:/etc/mysql/conf.d:ro

  redis:
    image: redis:6.2-alpine
    # restart: always
    ports:
      - 6379:6379
    volumes:
      - installdirectory/data/redis:/data

  mailtrap:
    build: mailtrap
    # restart: always
    ports:
      - 8085:8085
      - 0.0.0.0:25:25

  elasticsearch:
    build: elasticsearch
    # restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true

