version: "3"

networks:
  xcom_network:
    driver: bridge

volumes:
  elasticsearch:

services:
  nginx:
    build: nginx
    # restart: always
    ports:
      - 8080:80
      - 443:443
    working_dir: /etc/nginx/sites-enabled
    volumes:
      - ./nginx/site-templates:/etc/nginx/site-templates:ro
      - installdirectory/data/shared/sites:/data/shared/sites
      - installdirectory/data/shared/sockets:/data/shared/sockets
      - installdirectory/data/shared/media:/data/shared/media
      - /etc/xcomuser:/etc/xcomuser:ro
    networks:
      - xcom_network
  varnish:
    image: varnish:stable
    volumes:
      - "./varnish/default.vcl:/etc/varnish/default.vcl"
    ports:
      - "80:80"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G
    command: "-p default_keep=300"
    networks:
      - xcom_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "nginx"
  mysql57:
    image: mysql:5.7
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=xcom
    ports:
      - 3306:3306
    volumes:
      - installdirectory/data/mysql57:/var/lib/mysql
      - ./mysql57/conf.d:/etc/mysql/conf.d:ro
    networks:
      - xcom_network
  mysql80:
    image: mysql:8.0
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=xcom
    ports:
      - 3308:3308
    volumes:
      - installdirectory/data/mysql80:/var/lib/mysql
      - ./mysql80/conf.d:/etc/mysql/conf.d:ro
    networks:
      - xcom_network
  redis:
    image: redis:6.2-alpine
    # restart: always
    ports:
      - 6379:6379
    volumes:
      - installdirectory/data/redis:/data
    networks:
      - xcom_network
  mailtrap:
    build: mailtrap
    # restart: always
    ports:
      - 8085:8085
      - 0.0.0.0:25:25
    networks:
      - xcom_network
  elasticsearch:
    build: elasticsearch
    # restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
    networks:
      - xcom_network
